#[derive(Debug, Clone)]
pub struct ZoneMarker2D {
    pub zone_id: u16,
    pub markers: Vec<MarkerFlat>,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct MarkerFlat {
    pub position: Position3D,
    pub icon: String,
    pub size: u8,
    pub active: bool,
}

#[derive(Debug)]
pub struct MarkerRotatable {
    pub position: Position3D,
    pub rotation: Rotation3D,
    pub icon: String,
    pub size: u8,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct Position3D {
    pub x: i32,
    pub y: i32,
    pub z: i32,
}

#[derive(Debug)]
pub struct Rotation3D {
    pub pitch: f32,
    pub yaw: f32,
    pub roll: f32,
}

pub fn icon_number_to_string(icon_number: u16) -> String {
    match icon_number {
        1 => "1.png".to_string(),
        2 => "2.png".to_string(),
        3 => "3.png".to_string(),
        4 => "4.png".to_string(),
        5 => "5.png".to_string(),
        6 => "6.png".to_string(),
        7 => "7.png".to_string(),
        8 => "8.png".to_string(),
        9 => "9.png".to_string(),
        10 => "10.png".to_string(),
        11 => "11.png".to_string(),
        12 => "12.png".to_string(),
        13 => "arrow.png".to_string(),
        14 => "squares/marker_lightblue.png".to_string(),
        15 => "squares/square_blue.png".to_string(),
        16 => "squares/square_green.png".to_string(),
        17 => "squares/square_orange.png".to_string(),
        18 => "squares/square_orange_OT.png".to_string(),
        19 => "squares/square_pink.png".to_string(),
        20 => "squares/square_red.png".to_string(),
        21 => "squares/square_red_MT.png".to_string(),
        22 => "squares/square_yellow.png".to_string(),
        23 => "squares/squaretwo_blue.png".to_string(),
        24 => "squares/squaretwo_blue_one.png".to_string(),
        25 => "squares/squaretwo_blue_two.png".to_string(),
        26 => "squares/squaretwo_blue_three.png".to_string(),
        27 => "squares/squaretwo_blue_four.png".to_string(),
        28 => "squares/squaretwo_green.png".to_string(),
        29 => "squares/squaretwo_green_one.png".to_string(),
        30 => "squares/squaretwo_green_two.png".to_string(),
        31 => "squares/squaretwo_green_three.png".to_string(),
        32 => "squares/squaretwo_green_four.png".to_string(),
        33 => "squares/squaretwo_orange.png".to_string(),
        34 => "squares/squaretwo_orange_one.png".to_string(),
        35 => "squares/squaretwo_orange_two.png".to_string(),
        36 => "squares/squaretwo_orange_three.png".to_string(),
        37 => "squares/squaretwo_orange_four.png".to_string(),
        38 => "squares/squaretwo_pink.png".to_string(),
        39 => "squares/squaretwo_red.png".to_string(),
        40 => "squares/squaretwo_red_one.png".to_string(),
        41 => "squares/squaretwo_red_two.png".to_string(),
        42 => "squares/squaretwo_red_three.png".to_string(),
        43 => "squares/squaretwo_red_four.png".to_string(),
        44 => "squares/squaretwo_yellow.png".to_string(),
        45 => "a.png".to_string(),
        46 => "b.png".to_string(),
        47 => "c.png".to_string(),
        48 => "d.png".to_string(),
        49 => "e.png".to_string(),
        50 => "f.png".to_string(),
        51 => "g.png".to_string(),
        52 => "h.png".to_string(),
        53 => "i.png".to_string(),
        54 => "j.png".to_string(),
        55 => "k.png".to_string(),
        56 => "l.png".to_string(),
        57 => "m.png".to_string(),
        58 => "n.png".to_string(),
        59 => "o.png".to_string(),
        60 => "p.png".to_string(),
        61 => "q.png".to_string(),
        62 => "r.png".to_string(),
        63 => "s.png".to_string(),
        64 => "t.png".to_string(),
        65 => "u.png".to_string(),
        66 => "v.png".to_string(),
        67 => "w.png".to_string(),
        68 => "x.png".to_string(),
        69 => "y.png".to_string(),
        70 => "z.png".to_string(),
        71 => "sharkpog.png".to_string(),
        _ => "unknown.png".to_string(),
    }
}

pub fn string_to_icon_number(icon: &str) -> u16 {
    match icon {
        "1.png" => 1,
        "2.png" => 2,
        "3.png" => 3,
        "4.png" => 4,
        "5.png" => 5,
        "6.png" => 6,
        "7.png" => 7,
        "8.png" => 8,
        "9.png" => 9,
        "10.png" => 10,
        "11.png" => 11,
        "12.png" => 12,
        "arrow.png" => 13,
        "squares/marker_lightblue.png" => 14,
        "squares/square_blue.png" => 15,
        "squares/square_green.png" => 16,
        "squares/square_orange.png" => 17,
        "squares/square_orange_OT.png" => 18,
        "squares/square_pink.png" => 19,
        "squares/square_red.png" => 20,
        "squares/square_red_MT.png" => 21,
        "squares/square_yellow.png" => 22,
        "squares/squaretwo_blue.png" => 23,
        "squares/squaretwo_blue_one.png" => 24,
        "squares/squaretwo_blue_two.png" => 25,
        "squares/squaretwo_blue_three.png" => 26,
        "squares/squaretwo_blue_four.png" => 27,
        "squares/squaretwo_green.png" => 28,
        "squares/squaretwo_green_one.png" => 29,
        "squares/squaretwo_green_two.png" => 30,
        "squares/squaretwo_green_three.png" => 31,
        "squares/squaretwo_green_four.png" => 32,
        "squares/squaretwo_orange.png" => 33,
        "squares/squaretwo_orange_one.png" => 34,
        "squares/squaretwo_orange_two.png" => 35,
        "squares/squaretwo_orange_three.png" => 36,
        "squares/squaretwo_orange_four.png" => 37,
        "squares/squaretwo_pink.png" => 38,
        "squares/squaretwo_red.png" => 39,
        "squares/squaretwo_red_one.png" => 40,
        "squares/squaretwo_red_two.png" => 41,
        "squares/squaretwo_red_three.png" => 42,
        "squares/squaretwo_red_four.png" => 43,
        "squares/squaretwo_yellow.png" => 44,
        "a.png" => 45,
        "b.png" => 46,
        "c.png" => 47,
        "d.png" => 48,
        "e.png" => 49,
        "f.png" => 50,
        "g.png" => 51,
        "h.png" => 52,
        "i.png" => 53,
        "j.png" => 54,
        "k.png" => 55,
        "l.png" => 56,
        "m.png" => 57,
        "n.png" => 58,
        "o.png" => 59,
        "p.png" => 60,
        "q.png" => 61,
        "r.png" => 62,
        "s.png" => 63,
        "t.png" => 64,
        "u.png" => 65,
        "v.png" => 66,
        "w.png" => 67,
        "x.png" => 68,
        "y.png" => 69,
        "z.png" => 70,
        "sharkpog.png" => 71,
        _ => 14,
    }
}
